### PR TITLE
New look for index.html

### PR DESCRIPTION
**Pull request by tyrandus**
A new atmosphere for our dear playground.

### CODE REVIEW

**Comment by brainscript** [comment]
I was just doing the same ...
https://twitter.com/brnscrpt/status/826522486774849536

**Comment by brainscript** [comment]
@letsgamedev Which one should we take?

---
### My approach
first

### @Tyrandus's approach
second

**Comment by tyrandus** [comment]
Oh, I'm sorry. Yours is surely a great approach. In fact, I love this RPG style you included.

**Comment by letsgamedev** [comment]
Is it possible to see the real stuff? Like access the gh-page with your forks?

**Comment by brainscript** [comment]
@letsgamedev I don't think so, we would have to setup GitHub Pages first. You can quickly download the repos as a zip and open the indedx.html like I did.

**Comment by tyrandus** [comment]
Mine is online at: 
[https://tyrandus.github.io/spielsklave/](https://tyrandus.github.io/spielsklave/)

**Comment by brainscript** [comment]
@Tyrandus Same, https://brainscript.github.io/spielsklave/. :smile_cat:

**Comment by letsgamedev** [comment]
I really like the general style of @Tyrandus version. But it makes some problems with a narrow viewport like on mobile devices. 
The approach from @brainscript is a bit more robust but I don't like the background color and font. Also the YouTube link looks like THIS page IS the youTube page cause it looks "aktive"

Looks like you both can team up if you want to!

**Comment by brainscript** [comment]
@letsgamedev I would suggest that you merge @Tyrandus's version.
Then I can take a look at it and *"robustify"* it.

**Comment by tyrandus** [comment]
Great idea! Let's do this together.

**Comment by letsgamedev** [comment]
Merged it!
Big thanks for you participation to this project!

**Pull request merged**
